<?php
$data_google_voice = [
    ["name" => "en-US-Wavenet-A-MALE", "type_voice" => "en-US.en-US-Wavenet-A"],
    ["name" => "en-US-Wavenet-B-MALE", "type_voice" => "en-US.en-US-Wavenet-B"],
    ["name" => "en-US-Wavenet-C-FEMALE", "type_voice" => "en-US.en-US-Wavenet-C"],
    ["name" => "en-US-Wavenet-D-MALE", "type_voice" => "en-US.en-US-Wavenet-D"],
    ["name" => "en-US-Wavenet-E-FEMALE", "type_voice" => "en-US.en-US-Wavenet-E"],
    ["name" => "en-US-Wavenet-F-FEMALE", "type_voice" => "en-US.en-US-Wavenet-F"],
    ["name" => "en-US-Wavenet-G-FEMALE", "type_voice" => "en-US.en-US-Wavenet-G"],
    ["name" => "en-US-Wavenet-H-FEMALE", "type_voice" => "en-US.en-US-Wavenet-H"],
    ["name" => "en-US-Wavenet-I-MALE", "type_voice" => "en-US.en-US-Wavenet-I"],
    ["name" => "en-US-Wavenet-J-MALE", "type_voice" => "en-US.en-US-Wavenet-J"],
    ["name" => "en-US-Casual-K-MALE", "type_voice" => "en-US.en-US-Casual-K"],
    ["name" => "en-US-Neural2-A-MALE", "type_voice" => "en-US.en-US-Neural2-A"],
    ["name" => "en-US-Neural2-C-FEMALE", "type_voice" => "en-US.en-US-Neural2-C"],
    ["name" => "en-US-Neural2-D-MALE", "type_voice" => "en-US.en-US-Neural2-D"],
    ["name" => "en-US-Neural2-E-FEMALE", "type_voice" => "en-US.en-US-Neural2-E"],
    ["name" => "en-US-Neural2-F-FEMALE", "type_voice" => "en-US.en-US-Neural2-F"],
    ["name" => "en-US-Neural2-G-FEMALE", "type_voice" => "en-US.en-US-Neural2-G"],
    ["name" => "en-US-Neural2-H-FEMALE", "type_voice" => "en-US.en-US-Neural2-H"],
    ["name" => "en-US-Neural2-I-MALE", "type_voice" => "en-US.en-US-Neural2-I"],
    ["name" => "en-US-Neural2-J-MALE", "type_voice" => "en-US.en-US-Neural2-J"],
    ["name" => "en-US-News-K-FEMALE", "type_voice" => "en-US.en-US-News-K"],
    ["name" => "en-US-News-L-FEMALE", "type_voice" => "en-US.en-US-News-L"],
    ["name" => "en-US-News-N-MALE", "type_voice" => "en-US.en-US-News-N"],
    ["name" => "en-US-Polyglot-1-MALE", "type_voice" => "en-US.en-US-Polyglot-1"],
    ["name" => "en-AU-Wavenet-A-FEMALE", "type_voice" => "en-AU.en-AU-Wavenet-A"],
    ["name" => "en-AU-Wavenet-B-MALE", "type_voice" => "en-AU.en-AU-Wavenet-B"],
    ["name" => "en-AU-Wavenet-C-FEMALE", "type_voice" => "en-AU.en-AU-Wavenet-C"],
    ["name" => "en-AU-Wavenet-D-MALE", "type_voice" => "en-AU.en-AU-Wavenet-D"],
    ["name" => "en-AU-Neural2-A-FEMALE", "type_voice" => "en-AU.en-AU-Neural2-A"],
    ["name" => "en-AU-Neural2-B-MALE", "type_voice" => "en-AU.en-AU-Neural2-B"],
    ["name" => "en-AU-Neural2-C-FEMALE", "type_voice" => "en-AU.en-AU-Neural2-C"],
    ["name" => "en-AU-Neural2-D-MALE", "type_voice" => "en-AU.en-AU-Neural2-D"],
    ["name" => "en-AU-News-E-FEMALE", "type_voice" => "en-AU.en-AU-News-E"],
    ["name" => "en-AU-News-F-FEMALE", "type_voice" => "en-AU.en-AU-News-F"],
    ["name" => "en-AU-News-G-MALE", "type_voice" => "en-AU.en-AU-News-G"],
    ["name" => "en-AU-Polyglot-1-MALE", "type_voice" => "en-AU.en-AU-Polyglot-1"],
    ["name" => "en-IN-Neural2-A-FEMALE", "type_voice" => "en-IN.en-IN-Neural2-A"],
    ["name" => "en-IN-Neural2-B-MALE", "type_voice" => "en-IN.en-IN-Neural2-B"],
    ["name" => "en-IN-Neural2-C-MALE", "type_voice" => "en-IN.en-IN-Neural2-C"],
    ["name" => "en-IN-Neural2-D-FEMALE", "type_voice" => "en-IN.en-IN-Neural2-D"],
    ["name" => "en-IN-Wavenet-A-FEMALE", "type_voice" => "en-IN.en-IN-Wavenet-A"],
    ["name" => "en-IN-Wavenet-B-MALE", "type_voice" => "en-IN.en-IN-Wavenet-B"],
    ["name" => "en-IN-Wavenet-C-MALE", "type_voice" => "en-IN.en-IN-Wavenet-C"],
    ["name" => "en-IN-Wavenet-D-FEMALE", "type_voice" => "en-IN.en-IN-Wavenet-D"],
    ["name" => "en-GB-Neural2-A-FEMALE", "type_voice" => "en-GB.en-GB-Neural2-A"],
    ["name" => "en-GB-Neural2-B-MALE", "type_voice" => "en-GB.en-GB-Neural2-B"],
    ["name" => "en-GB-Neural2-C-FEMALE", "type_voice" => "en-GB.en-GB-Neural2-C"],
    ["name" => "en-GB-Neural2-D-MALE", "type_voice" => "en-GB.en-GB-Neural2-D"],
    ["name" => "en-GB-Neural2-F-FEMALE", "type_voice" => "en-GB.en-GB-Neural2-F"],
    ["name" => "en-GB-News-G-FEMALE", "type_voice" => "en-GB.en-GB-News-G"],
    ["name" => "en-GB-News-H-FEMALE", "type_voice" => "en-GB.en-GB-News-H"],
    ["name" => "en-GB-News-I-FEMALE", "type_voice" => "en-GB.en-GB-News-I"],
    ["name" => "en-GB-News-J-MALE", "type_voice" => "en-GB.en-GB-News-J"],
    ["name" => "en-GB-News-K-MALE", "type_voice" => "en-GB.en-GB-News-K"],
    ["name" => "en-GB-News-L-MALE", "type_voice" => "en-GB.en-GB-News-L"],
    ["name" => "en-GB-News-M-MALE", "type_voice" => "en-GB.en-GB-News-M"],
    ["name" => "en-GB-Wavenet-A-FEMALE", "type_voice" => "en-GB.en-GB-Wavenet-A"],
    ["name" => "en-GB-Wavenet-B-MALE", "type_voice" => "en-GB.en-GB-Wavenet-B"],
    ["name" => "en-GB-Wavenet-C-FEMALE", "type_voice" => "en-GB.en-GB-Wavenet-C"],
    ["name" => "en-GB-Wavenet-D-MALE", "type_voice" => "en-GB.en-GB-Wavenet-D"],
    ["name" => "en-GB-Wavenet-F-FEMALE", "type_voice" => "en-GB.en-GB-Wavenet-F"]
];








