<?php
$data_google_voice = [
    ["name" => "en-US-Wavenet-A-MALE", "type_voice" => "en-US.en-US-Wavenet-A.MALE"],
    ["name" => "en-US-Wavenet-B-MALE", "type_voice" => "en-US.en-US-Wavenet-B.MALE"],
    ["name" => "en-US-Wavenet-C-FEMALE", "type_voice" => "en-US.en-US-Wavenet-C.FEMALE"],
    ["name" => "en-US-Wavenet-D-MALE", "type_voice" => "en-US.en-US-Wavenet-D.MALE"],
    ["name" => "en-US-Wavenet-E-FEMALE", "type_voice" => "en-US.en-US-Wavenet-E.FEMALE"],
    ["name" => "en-US-Wavenet-F-FEMALE", "type_voice" => "en-US.en-US-Wavenet-F.FEMALE"],
    ["name" => "en-US-Wavenet-G-FEMALE", "type_voice" => "en-US.en-US-Wavenet-G.FEMALE"],
    ["name" => "en-US-Wavenet-H-FEMALE", "type_voice" => "en-US.en-US-Wavenet-H.FEMALE"],
    ["name" => "en-US-Wavenet-I-MALE", "type_voice" => "en-US.en-US-Wavenet-I.MALE"],
    ["name" => "en-US-Wavenet-J-MALE", "type_voice" => "en-US.en-US-Wavenet-J.MALE"],
    ["name" => "en-US-Casual-K-MALE", "type_voice" => "en-US.en-US-Casual-K.MALE"],
    ["name" => "en-US-Neural2-A-MALE", "type_voice" => "en-US.en-US-Neural2-A.MALE"],
    ["name" => "en-US-Neural2-C-FEMALE", "type_voice" => "en-US.en-US-Neural2-C.FEMALE"],
    ["name" => "en-US-Neural2-D-MALE", "type_voice" => "en-US.en-US-Neural2-D.MALE"],
    ["name" => "en-US-Neural2-E-FEMALE", "type_voice" => "en-US.en-US-Neural2-E.FEMALE"],
    ["name" => "en-US-Neural2-F-FEMALE", "type_voice" => "en-US.en-US-Neural2-F.FEMALE"],
    ["name" => "en-US-Neural2-G-FEMALE", "type_voice" => "en-US.en-US-Neural2-G.FEMALE"],
    ["name" => "en-US-Neural2-H-FEMALE", "type_voice" => "en-US.en-US-Neural2-H.FEMALE"],
    ["name" => "en-US-Neural2-I-MALE", "type_voice" => "en-US.en-US-Neural2-I.MALE"],
    ["name" => "en-US-Neural2-J-MALE", "type_voice" => "en-US.en-US-Neural2-J.MALE"],
    ["name" => "en-US-News-K-FEMALE", "type_voice" => "en-US.en-US-News-K.FEMALE"],
    ["name" => "en-US-News-L-FEMALE", "type_voice" => "en-US.en-US-News-L.FEMALE"],
    ["name" => "en-US-News-N-MALE", "type_voice" => "en-US.en-US-News-N.MALE"],
    ["name" => "en-US-Polyglot-1-MALE", "type_voice" => "en-US.en-US-Polyglot-1.MALE"],
    ["name" => "en-AU-Wavenet-A-FEMALE", "type_voice" => "en-AU.en-AU-Wavenet-A.FEMALE"],
    ["name" => "en-AU-Wavenet-B-MALE", "type_voice" => "en-AU.en-AU-Wavenet-B.MALE"],
    ["name" => "en-AU-Wavenet-C-FEMALE", "type_voice" => "en-AU.en-AU-Wavenet-C.FEMALE"],
    ["name" => "en-AU-Wavenet-D-MALE", "type_voice" => "en-AU.en-AU-Wavenet-D.MALE"],
    ["name" => "en-AU-Neural2-A-FEMALE", "type_voice" => "en-AU.en-AU-Neural2-A.FEMALE"],
    ["name" => "en-AU-Neural2-B-MALE", "type_voice" => "en-AU.en-AU-Neural2-B.MALE"],
    ["name" => "en-AU-Neural2-C-FEMALE", "type_voice" => "en-AU.en-AU-Neural2-C.FEMALE"],
    ["name" => "en-AU-Neural2-D-MALE", "type_voice" => "en-AU.en-AU-Neural2-D.MALE"],
    ["name" => "en-AU-News-E-FEMALE", "type_voice" => "en-AU.en-AU-News-E.FEMALE"],
    ["name" => "en-AU-News-F-FEMALE", "type_voice" => "en-AU.en-AU-News-F.FEMALE"],
    ["name" => "en-AU-News-G-MALE", "type_voice" => "en-AU.en-AU-News-G.MALE"],
    ["name" => "en-AU-Polyglot-1-MALE", "type_voice" => "en-AU.en-AU-Polyglot-1.MALE"],
    ["name" => "en-IN-Neural2-A-FEMALE", "type_voice" => "en-IN.en-IN-Neural2-A.FEMALE"],
    ["name" => "en-IN-Neural2-B-MALE", "type_voice" => "en-IN.en-IN-Neural2-B.MALE"],
    ["name" => "en-IN-Neural2-C-MALE", "type_voice" => "en-IN.en-IN-Neural2-C.MALE"],
    ["name" => "en-IN-Neural2-D-FEMALE", "type_voice" => "en-IN.en-IN-Neural2-D.FEMALE"],
    ["name" => "en-IN-Wavenet-A-FEMALE", "type_voice" => "en-IN.en-IN-Wavenet-A.FEMALE"],
    ["name" => "en-IN-Wavenet-B-MALE", "type_voice" => "en-IN.en-IN-Wavenet-B.MALE"],
    ["name" => "en-IN-Wavenet-C-MALE", "type_voice" => "en-IN.en-IN-Wavenet-C.MALE"],
    ["name" => "en-IN-Wavenet-D-FEMALE", "type_voice" => "en-IN.en-IN-Wavenet-D.FEMALE"],
    ["name" => "en-GB-Neural2-A-FEMALE", "type_voice" => "en-GB.en-GB-Neural2-A.FEMALE"],
    ["name" => "en-GB-Neural2-B-MALE", "type_voice" => "en-GB.en-GB-Neural2-B.MALE"],
    ["name" => "en-GB-Neural2-C-FEMALE", "type_voice" => "en-GB.en-GB-Neural2-C.FEMALE"],
    ["name" => "en-GB-Neural2-D-MALE", "type_voice" => "en-GB.en-GB-Neural2-D.MALE"],
    ["name" => "en-GB-Neural2-F-FEMALE", "type_voice" => "en-GB.en-GB-Neural2-F.FEMALE"],
    ["name" => "en-GB-News-G-FEMALE", "type_voice" => "en-GB.en-GB-News-G.FEMALE"],
    ["name" => "en-GB-News-H-FEMALE", "type_voice" => "en-GB.en-GB-News-H.FEMALE"],
    ["name" => "en-GB-News-I-FEMALE", "type_voice" => "en-GB.en-GB-News-I.FEMALE"],
    ["name" => "en-GB-News-J-MALE", "type_voice" => "en-GB.en-GB-News-J.MALE"],
    ["name" => "en-GB-News-K-MALE", "type_voice" => "en-GB.en-GB-News-K.MALE"],
    ["name" => "en-GB-News-L-MALE", "type_voice" => "en-GB.en-GB-News-L.MALE"],
    ["name" => "en-GB-News-M-MALE", "type_voice" => "en-GB.en-GB-News-M.MALE"],
    ["name" => "en-GB-Wavenet-A-FEMALE", "type_voice" => "en-GB.en-GB-Wavenet-A.FEMALE"],
    ["name" => "en-GB-Wavenet-B-MALE", "type_voice" => "en-GB.en-GB-Wavenet-B.MALE"],
    ["name" => "en-GB-Wavenet-C-FEMALE", "type_voice" => "en-GB.en-GB-Wavenet-C.FEMALE"],
    ["name" => "en-GB-Wavenet-D-MALE", "type_voice" => "en-GB.en-GB-Wavenet-D.MALE"],
    ["name" => "en-GB-Wavenet-F-FEMALE", "type_voice" => "en-GB.en-GB-Wavenet-F.FEMALE"]
];








